<a href="https://colab.research.google.com/github/sreemanjusha/perceptron/blob/main/Mine_Perceptron_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron

class percept():
  def __init__(self,epochs,eta):
    self.n_iter=epochs
    self.eta=eta
  
  def fit(self,X_train,Y_train):
    self.w_=np.zeros(1+X_train.shape[1])
    self.errors_=np.zeros((self.n_iter,))
    for epoch in np.arange(1,self.n_iter+1):
      errors_in_this_epoch=0
      for xi,yi in zip(X_train,Y_train):
        self.w_[1:]+=self.eta*(yi-self.predict(xi))*xi
        self.w_[0]+=self.eta*(yi-self.predict(xi))
        if(yi!=self.predict(xi)):
          errors_in_this_epoch+=1
      self.errors_[epoch-1]=(errors_in_this_epoch/X_train.shape[0])*100
    
  def predict(self,x):
      return np.where(self.net_input(x)>0,1,0)

  def net_input(self,x):
      return np.dot(x,self.w_[1:])+self.w_[0]



In [ ]:
df=pd.read_csv('/content/challenger.csv')
df

o_ring_ct  O.ring.failures  temperature  pressure  launch_id
0           6                0           66        50          1
1           6                1           70        50          2
2           6                0           69        50          3
3           6                0           68        50          4
4           6                0           67        50          5
5           6                0           72        50          6
6           6                0           73       100          7
7           6                0           70       100          8
8           6                1           57       200          9
9           6                1           63       200         10
10          6                1           70       200         11
11          6                0           78       200         12
12          6                0           67       200         13
13          6                2           53       200         14
14          6                0           67       200         15
15          6                0           75       200         16
16          6                0           70       200         17
17          6                0           81       200         18
18          6                0           76       200         19
19          6                0           79       200         20
20          6                0           75       200         21
21          6                0           76       200         22
22          6                1           58       200         23

In [ ]:
df['O.ring.failures'].replace(2,1,inplace=True)
df

o_ring_ct  O.ring.failures  temperature  pressure  launch_id
0           6                0           66        50          1
1           6                1           70        50          2
2           6                0           69        50          3
3           6                0           68        50          4
4           6                0           67        50          5
5           6                0           72        50          6
6           6                0           73       100          7
7           6                0           70       100          8
8           6                1           57       200          9
9           6                1           63       200         10
10          6                1           70       200         11
11          6                0           78       200         12
12          6                0           67       200         13
13          6                1           53       200         14
14          6                0           67       200         15
15          6                0           75       200         16
16          6                0           70       200         17
17          6                0           81       200         18
18          6                0           76       200         19
19          6                0           79       200         20
20          6                0           75       200         21
21          6                0           76       200         22
22          6                1           58       200         23

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.iloc[:,[0,2,3,4]].values
Y=df.iloc[:,1].values

In [ ]:
X

array([[  6,  66,  50,   1],
       [  6,  70,  50,   2],
       [  6,  69,  50,   3],
       [  6,  68,  50,   4],
       [  6,  67,  50,   5],
       [  6,  72,  50,   6],
       [  6,  73, 100,   7],
       [  6,  70, 100,   8],
       [  6,  57, 200,   9],
       [  6,  63, 200,  10],
       [  6,  70, 200,  11],
       [  6,  78, 200,  12],
       [  6,  67, 200,  13],
       [  6,  53, 200,  14],
       [  6,  67, 200,  15],
       [  6,  75, 200,  16],
       [  6,  70, 200,  17],
       [  6,  81, 200,  18],
       [  6,  76, 200,  19],
       [  6,  79, 200,  20],
       [  6,  75, 200,  21],
       [  6,  76, 200,  22],
       [  6,  58, 200,  23]])

In [ ]:
Y

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1])

In [ ]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
perc = percept(10,0.01)
t=perc.fit(X_train,Y_train)

In [ ]:
y_pred=perc.predict(X_test)
print(Y_test-y_pred)

[0 1 0 0 0]


In [ ]:
X_test

array([[  6,  78, 200,  12],
       [  6,  70, 200,  11],
       [  6,  76, 200,  22],
       [  6,  67, 200,  15],
       [  6,  75, 200,  21]])

In [ ]:
Y_pred

array([0, 0, 0, 0, 0])

In [ ]:
Y_test

array([0, 1, 0, 0, 0])

In [ ]:
print(perc.errors_)

[ 5.55555556 11.11111111  5.55555556  5.55555556  5.55555556  5.55555556
  5.55555556  5.55555556  5.55555556  5.55555556]


In [ ]:
print(perc.fit(X_train,Y_train))

None
